# import time
#
# import pytest
#
# from selenium import webdriver
# from selenium.webdriver import Keys, ActionChains
# from selenium.webdriver.chrome.service import Service as ChromeService
# from selenium.webdriver.common.by import By
# from selenium.webdriver.firefox.options import Options as FireFoxOptions
# from selenium.webdriver.firefox.service import Service as FirefoxService
#
# from selenium.webdriver.chrome.options import Options as ChromeOptions
# from selenium.webdriver.support.wait import WebDriverWait
# from selenium.webdriver.support import expected_conditions as EC

import random
import time
import pytest
from select import select
from selenium.webdriver.support.select import Select

from selenium.common import NoSuchElementException, ElementNotInteractableException, InvalidElementStateException, \
    ElementNotVisibleException, StaleElementReferenceException, TimeoutException
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome import webdriver
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.firefox.options import Options as FireFoxOptions
from selenium.webdriver.firefox.service import Service as FirefoxService


from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities



@pytest.fixture()
def driver():
    chrome_driver_binary = "chromedriver.exe"
    ser_chrome = ChromeService(chrome_driver_binary)
    driver = webdriver.Chrome(service=ser_chrome)
    yield driver
    driver.close()
#
# def test_buy_product_without_account(driver):
#     driver.get("http://127.0.0.1:8000/#/")
#     driver.execute_script(
#         "document.querySelector('#root > div > main > div > div:nth-child(3) > div > div:nth-child(1) > div > div > a > div > strong').scrollIntoView();")
#     time.sleep(1)
#     driver.find_element(By.CSS_SELECTOR,
#                         "#root > div > main > div > div:nth-child(3) > div > div:nth-child(1) > div > div > a > div > strong").click()
#     # driver.execute_script("window.scrollTo(0,247)")
#     time.sleep(1)
#     driver.execute_script(
#         "document.querySelector('#root > div > main > div > div > div:nth-child(1) > div.col > div > div > div:nth-child(4) > button').scrollIntoView();")
#     time.sleep(1)
#     driver.find_element(By.CSS_SELECTOR,
#                               "#root > div > main > div > div > div:nth-child(1) > div.col > div > div > div:nth-child(4) > button").click()
#     time.sleep(1)
#     driver.find_element(By.CSS_SELECTOR, ".col-md-3 > .form-control").click()
#     dropdown = driver.find_element(By.CSS_SELECTOR, ".col-md-3 > .form-control")
#     dropdown.find_element(By.XPATH, "//option[. = '2']").click()
#     driver.find_element(By.CSS_SELECTOR, ".w-100").click()
#     assert driver.current_url == "http://127.0.0.1:8000/#/login?redirect=shipping"



# def test_buy_product_with_account_after_logged_in(driver):
#     driver.get("http://127.0.0.1:8000/#/")
#     driver.maximize_window()
#     driver.find_element(By.CSS_SELECTOR, ".nav-link:nth-child(2)").click()
#     driver.find_element(By.ID, "email").click()
#     driver.find_element(By.ID, "email").send_keys("tamer.tester@gmail.com")
#     driver.find_element(By.ID, "password").click()
#     driver.find_element(By.ID, "password").send_keys("assi12345")
#     time.sleep(3)
#     driver.find_element(By.XPATH, "//*[@id='root']/div/main/div/div/div/form/button").click()
#     time.sleep(3)
#     driver.execute_script(
#         "document.querySelector('#root > div > main > div > div:nth-child(3) > div > div:nth-child(1) > div > div > a > div > strong').scrollIntoView();")
#     time.sleep(1)
#     driver.find_element(By.CSS_SELECTOR,
#                         "#root > div > main > div > div:nth-child(3) > div > div:nth-child(1) > div > div > a > div > strong").click()
#     # driver.execute_script("window.scrollTo(0,247)")
#     time.sleep(1)
#     driver.execute_script(
#         "document.querySelector('#root > div > main > div > div > div:nth-child(1) > div.col > div > div > div:nth-child(4) > button').scrollIntoView();")
#     time.sleep(1)
#     driver.find_element(By.CSS_SELECTOR,
#                         "#root > div > main > div > div > div:nth-child(1) > div.col > div > div > div:nth-child(4) > button").click()
#     time.sleep(1)
#     driver.find_element(By.CSS_SELECTOR, ".col-md-3 > .form-control").click()
#     dropdown = driver.find_element(By.CSS_SELECTOR, ".col-md-3 > .form-control")
#     dropdown.find_element(By.XPATH, "//option[. = '2']").click()
#     driver.find_element(By.CSS_SELECTOR, ".w-100").click()
#     time.sleep(1)
#     driver.find_element(By.CSS_SELECTOR, ".justify-content-md-center").click()
#     driver.find_element(By.ID, "address").click()
#     driver.find_element(By.ID, "address").send_keys("Kfar bara")
#     driver.find_element(By.ID, "city").click()
#     driver.find_element(By.ID, "city").send_keys("Kfar bara")
#     # driver.find_element(By.ID, "postalCode").click()
#     # driver.find_element(By.ID, "postalCode").click()
#     driver.find_element(By.ID, "postalCode").click()
#     element = driver.find_element(By.ID, "postalCode")
#     actions = ActionChains(driver)
#     actions.double_click(element).perform()
#     driver.find_element(By.ID, "postalCode").send_keys("16000")
#     driver.find_element(By.ID, "country").click()
#     # driver.find_element(By.ID, "country").click()
#     # element = driver.find_element(By.ID, "country")
#     # actions = ActionChains(driver)
#     # actions.double_click(element).perform()
#     # driver.find_element(By.ID, "country").click()
#     driver.find_element(By.ID, "country").send_keys("Israel")
#     driver.execute_script(
#         "document.querySelector('#root > div > main > div > div > div > form > button').scrollIntoView();")
#     time.sleep(1)
#     driver.find_element(By.CSS_SELECTOR, "#root > div > main > div > div > div > form > button").click()
#     # driver.find_element(By.CSS_SELECTOR, ".my-3").click()
#     driver.find_element(By.CSS_SELECTOR, "#root > div > main > div > div > div > form > button").click()
#     driver.find_element(By.CSS_SELECTOR,
#                         "#root > div > main > div > div.row > div.col-md-4 > div > div > div:nth-child(7) > button").click()
#     time.sleep(2)
#     order_name = driver.find_element(By.CSS_SELECTOR, "#root > div > main > div > h1")
#
#     assert order_name.is_displayed()


# def test_buy_product_changing_total_price_with_changing_quantity(driver):
#     driver.get("http://127.0.0.1:8000/#/")
#     driver.maximize_window()
#     driver.find_element(By.CSS_SELECTOR, ".nav-link:nth-child(2)").click()
#     driver.find_element(By.ID, "email").click()
#     driver.find_element(By.ID, "email").send_keys("tamer.tester@gmail.com")
#     driver.find_element(By.ID, "password").click()
#     driver.find_element(By.ID, "password").send_keys("assi12345")
#     driver.find_element(By.CSS_SELECTOR, ".mt-3").click()
#     time.sleep(4)
#     driver.execute_script(
#         "document.querySelector('#root > div > main > div > div:nth-child(3) > div > div:nth-child(1) > div > div > a > div > strong').scrollIntoView();")
#     time.sleep(1)
#     driver.find_element(By.CSS_SELECTOR,
#                         "#root > div > main > div > div:nth-child(3) > div > div:nth-child(1) > div > div > a > div > strong").click()
#     # driver.execute_script("window.scrollTo(0,247)")
#     time.sleep(2)
#     driver.execute_script(
#         "document.querySelector('#root > div > main > div > div > div:nth-child(1) > div.col > div > div > div:nth-child(4) > button').scrollIntoView();")
#     time.sleep(1)
#     driver.find_element(By.CSS_SELECTOR,
#                         "#root > div > main > div > div > div:nth-child(1) > div.col > div > div > div:nth-child(4) > button").click()
#     time.sleep(1)
#     driver.find_element(By.CSS_SELECTOR, ".col-md-3 > .form-control").click()
#     dropdown = driver.find_element(By.CSS_SELECTOR, ".col-md-3 > .form-control")
#     time.sleep(5)
#     dropdown.find_element(By.XPATH, "//option[. = '2']").click()
#     time.sleep(5)
#     price_for_one_string = driver.find_element(By.CSS_SELECTOR,
#                                                "#root > div > main > div > div.col-md-8 > div > div > div > div:nth-child(3)").text
#     time.sleep(5)
#     price_for_one = float(price_for_one_string[1:])
#     time.sleep(5)
#     total_price_string = driver.find_element(By.CSS_SELECTOR,
#                                              "#root > div > main > div > div.col-md-4 > div > div.list-group.list-group-flush > div").text
#     total_price = float(total_price_string[-7:])
#
#     assert total_price == (2 * price_for_one)
#
#
